language: cpp
compiler:
- gcc
- clang
os:
- linux
- osx
before_install:
- uname
- cmake --version
- clang --version
script:
- cmake -Bbuild -H. -DUNIT-TESTS:BOOL=ON
- cmake --build build --target timers-tests --config Release
after_success:
branches:
  only:
notifications:
  email: false
env:
  global:
