language: cpp
compiler:
- clang
os:
- linux
before_install:
- uname
- cmake --version
- clang --version
#- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies.sh; fi
#- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm38 && brew install openssl && brew link --force --overwrite llvm38; fi
script:
- cmake -Bbuild -H. -DUNIT-TESTS:BOOL=ON
- cmake --build --config Release
after_success:
branches:
  only:
notifications:
  email: false
env:
  global:
