jobs:
  include:
    - stage: build example
      language: cpp
      compiler:
        - gcc
        - clang
      os:
        - osx
      script:
        - echo "a"
    - stage: build tests
      script:
        - echo "b"
