language: cpp
compiler:
- gcc
- clang
os:
- linux
- osx
before_install:
- cmake --version
- gcc --version
- clang --version
jobs:
  include:
    - stage: build-example
      script:
        - echo "a"
    - stage: build-tests
      script:
        - echo "b"
