stages:
  - build example
  - build tests
  - run tests

jobs:
  include:
    - stage: build example
      language: cpp
      compiler:
        - gcc
        - clang
      os:
        - osx
      script:
        - cmake -Bbuild -H. -DEXAMPLE:BOOL=ON -DUNIT-TESTS:BOOL=OFF
        - cmake --build ./build --target example --config Release

    - stage: build tests
      language: cpp
      compiler:
        - gcc
        - clang
      os:
        - osx
      script:
        - cmake -Bbuild -H. -DEXAMPLE:BOOL=OFF -DUNIT-TESTS:BOOL=ON
        - cmake --build ./build --target tests --config Release

    - stage: run tests
      language: cpp
      os:
        - osx
      script:
        - echo "run tests"
